services:
  node-init:
    image: "node:21-alpine"
    command: "npm install"
    working_dir: /app
    volumes:
      - ./src/server:/app

  node-server:
    image: "node:21-alpine"
    network_mode: host
    command: "node --watch --trace-warnings server-index.js"
    working_dir: /app
    volumes:
      - ./src/server:/app

    depends_on:
      node-init:
        condition: service_completed_successfully

  node-init-2:
    image: "node:21-alpine"
    command: "npm install"
    working_dir: /app
    volumes:
      - ./src/client:/app

  node-server-2:
    image: "node:21-alpine"
    network_mode: host
    command: "node --watch --trace-warnings client-index.js"
    working_dir: /app
    volumes:
      - ./src/client:/app

    depends_on:
      node-init-2:
        condition: service_completed_successfully