services:
  node-init:
    image: "node:18-alpine"
    command: "npm install"
    working_dir: /app
    volumes:
      - ./src/server:/app

  node-server:
    image: "node:18-alpine"
    command: "node --watch --trace-warnings server-index.js"
    ports: 
      - "25255:8080"
    working_dir: /app
    volumes:
      - ./src/server:/app

    depends_on:
      node-init:
        condition: service_completed_successfully

  node-init-2:
    image: "node:18-alpine"
    command: "npm install"
    working_dir: /app
    volumes:
      - ./src/client:/app

  node-server-2:
    image: "node:18-alpine"
    command: "node --watch --trace-warnings client-index.js"
    ports: 
      - "25256:8080"
    working_dir: /app
    volumes:
      - ./src/client:/app

    depends_on:
      node-init-2:
        condition: service_completed_successfully